name = "ProximalDistanceAlgorithms"
uuid = "941a68e6-59f4-4a05-b424-3010d949214d"
authors = ["Alfonso Landeros <alanderos@ucla.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SparseArrays", "Test"]
